FROM public.ecr.aws/lambda/python:3.11
COPY requirements.txt ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements.txt --upgrade
EXPOSE 8000

COPY src/* ${LAMBDA_TASK_ROOT}
COPY src/app ${LAMBDA_TASK_ROOT}/app
